name: "1 - [FEAT] PR"

on:
  push:
    branches:
      - "qa"
  
jobs:
  code-scan:
    uses: ./.github/workflows/sonarqube.yaml
    with:
      environment: feature
    secrets: inherit

  monitor:
    uses: ./.github/workflows/monitor-jobs.yaml
    needs:
      - code-scan
    with:
      app: app-template
      job-name: code-scan / Scan
    secrets: inherit